import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutProvider from "./Provider";
// import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });
type Props = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  const MainWrapper = ({ children }: Props) => {
    return (
      <main className="bg-[#f4e8ee] m-[10px] p-[10px] flex flex-col items-center ">
        <div className="flex justify-center bg-white mx-4 my-8 py-[60px] w-[900px] h-dvh">
          {children}
        </div>
      </main>
    );
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProvider>
          <MainWrapper>
            {children}
            {/* <ToastContainer /> */}
          </MainWrapper>
        </LayoutProvider>
      </body>
    </html>
  );
}
